services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '100GB'
    shm_size: '100GB'
    image: qa_mid
    container_name: qa_mid
    volumes:
      - /home/deguchi/qa_molecular_inverse_design:/qa_mid
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
